services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: phda_dev
      POSTGRES_USER: phda_user
      POSTGRES_PASSWORD: phda_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phda_user -d phda_dev"]
      interval: 10s
      timeout: 3s
      retries: 3

  ai-data-logger:
    build: 
      context: .
      dockerfile: services/ai-data-logger/Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://phda_user:phda_password@db:5432/phda_dev
    volumes:
      - ./services/ai-data-logger:/app/services/ai-data-logger
      - ./shared:/app/shared
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: