"""create initial health tables

Revision ID: 20380b70e496
Revises: 
Create Date: 2025-07-30 12:24:01.283080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20380b70e496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=False),
    sa.Column('alcohol_oz', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_lb', sa.Float(), nullable=False),
    sa.Column('smm_lb', sa.Float(), nullable=False),
    sa.Column('pbf', sa.Float(), nullable=False),
    sa.Column('ecw_tcw', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caffeine_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=False),
    sa.Column('caffeine_mg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heart_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('systolic_mmhg', sa.Integer(), nullable=False),
    sa.Column('diastolic_mmhg', sa.Integer(), nullable=False),
    sa.Column('rate_bpm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('potassium_mg', sa.Float(), nullable=False),
    sa.Column('long_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sauna_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sauna_log')
    op.drop_table('nutrition_log')
    op.drop_table('heart_log')
    op.drop_table('caffeine_log')
    op.drop_table('body_log')
    op.drop_table('alcohol_log')
    # ### end Alembic commands ###