"""add optional temperature_f to sauna_log

Revision ID: 6b31158ca1b9
Revises: 20380b70e496
Create Date: 2025-08-01 10:25:37.804498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b31158ca1b9'
down_revision = '20380b70e496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sauna_log', sa.Column('temperature_f', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sauna_log', 'temperature_f')
    # ### end Alembic commands ###